### ISSUE TITLE
Buchstabieren - wrong Answer Task Event

### ISSUE THREAD

**Issue by JohannDch** [thm-mni-ii/lama#18]
Wenn ein oder mehrere falsche Buchstaben angetippt werden, soll die Aufgabe als falsch gewertet werden

**Comment by 35Art37ur** [comment]
hier soll die Anzahl der Fehler variabel werden und sowohl von der Klasse des Users , als auch von der Anzahl der Buchstaben abhängig sein

**Comment by 35Art37ur** [comment]
laut Prof. Kammer sollte ein Fehler erlaubt sein(bei der ersten Klasse), ansonsten keiner
Zusätzlich soll die erlaubte Fehlerzahl aus der JSON herausgelesen werden können.
PS: Variable maxFehlerAnzahl ist nun vorhanden und wird im Code auch schon verwendet
